# --- Serving options --- #

# GitHub user page settings:
url: "http://thomased.github.io"
baseurl: ""

# Name of website
title: Thomas White
subtitle: Evolution // Ecology // Behaviour

# Short description of your site
description: Evolutionary biologist

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon-2.png"

# List of links in the navigation bar
navbar-links:
  About: "index"
  Projects: "projects"
  Publications: "publications"
  Presentations: "presentations"
  Resources: "resources"
  Blog: "blog"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Thomas White
  email: "thomas.white@mq.edu.au"
  github: thomased
  twitter: tomedwhite     
 
# Select which links to show in the footer
footer-links-active:
  email: true
  twitter: true
  github: true

google_analytics: "UA-62544976-1"  

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Australia/Sydney"
markdown: redcarpet
highlighter: pygments
permalink: /:year-:month-:day-:title
paginate: 7


# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
